### get index
GET http://localhost:8080/

### update user
PATCH http://localhost:8081/
Content-Type: application/json

{
    "age":18
}

### update user
PATCH http://localhost:8080/
Content-Type: application/json

{
    "skills":["Go","Rust"]
}
